### ISSUE TITLE
Cannot find Walkinside SDK in example projects solution

### ISSUE THREAD

**Issue by griemens** [walkinside/sdk#5] opened 2016-11-08 14:44 UTC
Encounter a strange error when trying to build the example projects:
1. I open examples\official\Viewer SDK\ViewerSdkExamples.sln solution in Visual Studio 2012 professional all the projects open without errors. 
2. When I rebuild I have the error "Cannot find Walkinside SDK"
From the references I can see all referenced assemblies with yellow icon (Also Syste, System.Core etc ..)
3. When removing WalkinsideSDK.dll and adding it again from "C:\Program Files\COMOS\COMOS Walkinside 10.2 (64 bit)\WalkinsideSDK2.dll" it does not solve the build problem. Still have "Cannot find Walkinside SDK"

My setup Windows 7 and I have Walkinside 10.2 (64bits) installed for "All Users". Walkinside 32 bits is not installed.

**Comment by kveretennicov** [comment] 2016-11-08 16:53
Thank you. This looks like a bug in our Visual Studio projects that happens only when Walkinside is installed for "All Users". We will try to come up with a fix; meanwhile the workaround is to use "Just Me" Walkinside installation, if possible. (Or manually update assembly references in all example projects). 

I cannot check at the moment, but I suspect it's a permission issue with `Program Files` folder and we may not be able to support "All Users" installation as well as "Just Me". You can see [here](/walkinside/sdk/blob/master/examples/official/Viewer SDK/ViewerSdkExamples.User.Properties.proj) that we try to locate Walkinside installation path and then set assembly references accordingly. We also set build output path in such way that the compiled example plug-ins deploy right next to Walkinside binaries. In case of "All Users" installation this means building into `Program Files\...`, so I expect it will only work if Visual Studio is started "as Administrator". It's far from ideal, but may be a viable workaround for some.

**Comment by griemens** [comment] 2016-11-08 20:04
Thanks for the tip. 
- Installed Walkinside with option "Just me" and all works fine now.

Also tried launching Visual studio as admin and open project, but had same issue with "All Users" install.

**Comment by kveretennicov** [comment] 2016-11-14 15:42
The issue is due to 32-bit Visual Studio trying to read a 64-bit HKLM key to learn Walkinside installation path. Looks like we can fix it with [GetRegistryValueFromView](https://msdn.microsoft.com/en-us/library/dd633440.aspx?f=255&MSPPError=-2147217396#BKMK_GetRegistryValueFromView).

After that the next issue will be lack of permissions to build the plug-in directly into `C:\Program Files\...\Walkinside\plugins\application`. For this the developer will have to run Visual Studio as Administrator, which is pretty awkward, yet I don't see another way.

**Comment by kveretennicov** [comment] 2016-11-23 11:46
This will be resolved by requiring "Just Me" installation to use SDK examples. Example projects will give a helpful error message in case "Just Me" installation is not detected.

**Comment by griemens** [comment] 2016-12-01 20:04
Thanks, showing an error message and a tip how to solve would be excellent for me.
It would be a time saver.

**Comment by kveretennicov** [comment] 2016-12-02 17:29
We will upload SDK package for 10.2 SP1 beta next week, with this and some other changes.

**Comment by kveretennicov** [comment] 2016-12-08 20:31
This issue is normally resolved in beta release https://github.com/walkinside/sdk-beta/releases/tag/from-3336.

**Closed by kveretennicov** 2016-12-08 20:31 UTC
Labels: bug, has-workaround
